from typing import Annotated, List, Dict, Any
from typing_extensions import TypedDict
import pandas as pd
from langchain_core.tools import tool
import os

@tool
def output_placeholder(input: str) -> str:
    """
    This is a placeholder tool that will be used for output later.
    As of now it just returns a basic string.
    Later it will output code, analysis, and anything else generated by the agent into
    markdown, html, or pdf formats

    :param input:
        String input
    :return:
    """
    return f" I am the output_placeholder tool and this is the response to the {input}"